Accounts/urls.py
from django.urls import path , include
from . import views

app_name = "Accounts"
urlpatterns = [
    path('signup/',views.signup_view, name="signup"),
    path('login/',views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register_view, name="register"),
    path('profile/', views.profile_view, name="profile"),
]

Analyser/urls.py
from django.urls import path , include
from . import views

app_name = "Analyser"
urlpatterns = [
	path('', views.home, name="home"),
	path('analyseTweets', views.analyseTweets , name="analyseTweets"),
	path('showTweets', views.showTweets, name="showTweets"),
]

Dashboard/urls.py
from django.urls import path , include
from . import views

app_name = "Dashboard"
urlpatterns = [
	path('', views.home, name="home"),
	path('feedback/', views.feedback, name="feedback"),
]

Tweesy/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "Tweesy"

urlpatterns = [
    path('', views.home_view, name='home'),
	path('Accounts/', include('Accounts.urls')),
    path('Analyser/', include('Analyser.urls')),
    path('Dashboard/', include('Dashboard.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>TweeSy</title>
        
        <link href="{% static '/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    </head>
    <body>
          <nav class="navbar navbar-expand-sm bg-light navbar-light">
                <!-- Brand -->
                <a class = "navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'Logo.png' %}" alt="" style="max-height:50px;" />
                </a>
                <!-- Links -->
                <ul class ="nav navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Analyser:home' %}">Analyze</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Dashboard:home' %}">Dashboard</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav ml-auto" style="padding-right: 7%;">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <form class="form-inline float-right" action="#">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                                <button class="btn btn-success" type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </li>                        
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"><i class="fa fa-2x fa-user" aria-hidden="true"></i></a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i> Home</a>
                            {% if user.is_authenticated %}
                                    <a class="dropdown-item" href="{% url 'Accounts:profile' %}"><i class="fa fa-user" aria-hidden="true"></i> Profile</a>  
                                    <a class="dropdown-item" href="{% url 'Accounts:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout </a>
                            {% else %}
                                    <a class="dropdown-item" href="{% url 'Accounts:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>
                                    <a class="dropdown-item" href="{% url 'Accounts:signup' %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Signup</a>
                            {% endif %}
                            
                        </div>
                    </li>        
                </ul>
              </nav>
        <!-- <div class="container" style="width: 100%;"> -->
            qwerty
            qwert@1234
            {% block content %}
            {% endblock %}
        <!-- </div> -->
    </body>
</html>

templates/homePage.html
{% extends 'base_layout.html' %}

{% block content %}
		<h1>This is the home page for Tweesy Website</h1>
{% endblock %}	